### ISSUE TITLE
savePlaylist()

### ISSUE THREAD

**Issue by mp1pro** [bahobab/jammming#1]
Within the app class, the `Spotify.savePlaylist() `method should contain the setState method. That is the better practice. `playlistTracks: []` should also be resetted instead of `searchResults: []`. For example

```
  savePlaylist() {
    const trackUris = this.state.playlistTracks.map(track => track.uri);
    Spotify.savePlaylist(this.state.playlistName, trackUris).then(() => {
      this.setState({
        playlistName: 'New Playlist',
        playlistTracks: []
      });
    });
}
```

**Comment by bahobab** [comment]
Your're right. I confused playlistTracks with searchResults (I was using this solutions for debuging and did not revert it back for the final version). Thanks.
