### ISSUE TITLE
Named Imports

### ISSUE THREAD

**Issue by mp1pro** [bahobab/jammming#2]
The searchBar class was done doing a named export
`export default class SearchBar extends Component {`
It is a better practice to match it with a named import like so in app.js
`import {SearchBar} from '../SearchBar/SearchBar';`

same for other components

**Comment by bahobab** [comment]
Now, that applies to all other import statements then. Is it because I combined the "export default" in the class definition that I need a named import (as opposed to having a "exports default" at the bottom) ?

**Comment by mp1pro** [comment]
Yes, you can see some examples here. https://medium.com/@timoxley/named-exports-as-the-default-export-api-670b1b554f65
For further assistance, please contact a react adviser at http://codecademy.com

**Comment by bahobab** [comment]
Great. Thanks Marvin for everything.
Konan

On Nov 29, 2017 2:00 PM, Marvin Parke <notifications@github.com> wrote:

Yes, you can see some examples here. https://medium.com/@timoxley/named-exports-as-the-default-export-api-670b1b554f65
For further assistance, please contact a react adviser at http://codecademy.com
