### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [bahobab/jammming#4]
The project came out very well. most of the issues I saw did not cause an error, but could be a problem when you try to scale the project and add more components. The only thing I would suggest is mastering the state and setState feature. You can get more information on that here;
https://facebook.github.io/react-vr/docs/components-props-and-state.html

**Comment by bahobab** [comment]
Thanks a lot Marvin for your review, advice and great pointers to improve on my programming skills. Konan
